### ISSUE TITLE
info.message check before log

### ISSUE THREAD

**Issue by Rhymen** [OutOfSyncStudios/winston-logstash-transport#17]
Hey,

I started using this transport, but noticed, that some of my logs went missing. After debugging I saw, that only logs with a message property are logged properly. Is there a reason for the message property check in the log function?

I will create an PR, just wanted to make sure this is not actually for some intended reason.

**Comment by goodeath** [comment]
It's because of logstash.conf.

Filter json **source** property is usually set as message. I think that's why the if.  I couldn't find any good logstash winston transport. So I'm trying to use Bunyan with this [stream](https://github.com/transcovo/bunyan-logstash-tcp)

PS: Yeah, I could make my own transport, but I'm in an hurry now
